<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="H4877CC0001" failures="1" tests="2" name="ar.com.bna.digitaltest.testcases.LoginTest2" time="103.798" errors="1" timestamp="2024-10-07T12:39:39 GMT-03:00" skipped="0">
  <testcase classname="ar.com.bna.digitaltest.testcases.LoginTest2" name="enterValidCredentialsAndLogin" time="53.489">
    <error message="Cannot invoke &quot;org.openqa.selenium.WebElement.getText()&quot; because the return value of &quot;ar.com.bna.digitaltest.pages.BasePage.getWebElement(org.openqa.selenium.By)&quot; is null" type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException: Cannot invoke "org.openqa.selenium.WebElement.getText()" because the return value of "ar.com.bna.digitaltest.pages.BasePage.getWebElement(org.openqa.selenium.By)" is null
at ar.com.bna.digitaltest.pages.HomePage.getSaludoCliente(HomePage.java:16)
at ar.com.bna.digitaltest.testcases.LoginTest2.enterValidCredentialsAndLogin(LoginTest2.java:21)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1575)
]]>
    </error>
  </testcase> <!-- enterValidCredentialsAndLogin -->
  <system-out/>
  <testcase classname="ar.com.bna.digitaltest.testcases.LoginTest2" name="enterInvalidCredentialsAndLogin" time="50.309">
    <failure message="El mensaje de error no está desplegado expected [false] but found [true]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: El mensaje de error no está desplegado expected [false] but found [true]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertFalse(Assert.java:67)
at ar.com.bna.digitaltest.testcases.LoginTest2.enterInvalidCredentialsAndLogin(LoginTest2.java:33)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1575)
]]>
    </failure>
  </testcase> <!-- enterInvalidCredentialsAndLogin -->
  <system-out/>
</testsuite> <!-- ar.com.bna.digitaltest.testcases.LoginTest2 -->
